feat: dev image release test01

diff --git a/.github/workflows/create-dev-image-version-push-ecr.yaml b/.github/workflows/create-dev-image-version-push-ecr.yaml
--- a/.github/workflows/create-dev-image-version-push-ecr.yaml
+++ b/.github/workflows/create-dev-image-version-push-ecr.yaml
@@ -11,106 +11,15 @@ on:
 env:
   REPOSITORY: apha/bst
 jobs:
-  build-and-analyze:
-    name: Build + Test + Sonar
-    runs-on: windows-latest
+  push-image:
+    name: Push Docker Image
+    runs-on: ubuntu-latest
     environment: DEV   # 👈 restrict this job to DEV environment
     permissions:
       id-token: write
-      contents: write
-      pull-requests: write
-    outputs:
-      image_tag: ${{ steps.imgtag.outputs.image_tag }}
+      contents: read
+    
     steps:
-      - name: Set up JDK 17
-        uses: actions/setup-java@v4
-        with:
-          java-version: 17
-          distribution: zulu
-      - name: Checkout repository
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-          ref: ${{ github.ref_name }}
-          
-      - name: Cache SonarQube Cloud packages
-        uses: actions/cache@v4
-        with:
-          path: ~\sonar\cache
-          key: ${{ runner.os }}-sonar
-          restore-keys: ${{ runner.os }}-sonar
-      - name: Cache SonarQube Cloud scanner
-        id: cache-sonar-scanner
-        uses: actions/cache@v4
-        with:
-          path: .\.sonar\scanner
-          key: ${{ runner.os }}-sonar-scanner
-          restore-keys: ${{ runner.os }}-sonar-scanner
-      - name: Install SonarQube Cloud scanner
-        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
-        shell: pwsh
-        run: |
-          New-Item -Path .\.sonar\scanner -ItemType Directory
-          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
-
-      - name: Start Sonar Analysis
-        shell: pwsh
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: |
-          .\.sonar\scanner\dotnet-sonarscanner begin `
-            /k:"DEFRA_apha-bst" `
-            /o:"defra" `
-            /d:sonar.token="$env:SONAR_TOKEN" `
-            /d:sonar.host.url="https://sonarcloud.io" `
-            /v:"${{ steps.imgtag.outputs.image_tag }}" `
-            /d:sonar.cs.opencover.reportsPaths="src/TestResults/*.coverage.opencover.xml" `
-            /d:sonar.cs.vstest.reportsPaths="src/TestResults/*.test_results.trx" `
-            /d:sonar.branch.name="${{ github.ref_name }}" `
-            /d:sonar.verbose=true `
-            /d:sonar.exclusions="**/wwwroot/**" `
-            /d:sonar.coverage.exclusions="**/wwwroot/**,**/*.cshtml,**/Interfaces/*.cs,**/*Map.cs,**/*Mapper.cs,**/Program.cs,**/Startup.cs"
-      - name: Restore NuGet packages
-        shell: pwsh
-        run: dotnet restore src/Apha.BST.sln
-      - name: Build Solution
-        shell: pwsh
-        run: dotnet build src/Apha.BST.sln --configuration Release
-      - name: Run Unit Tests with Coverage
-        shell: pwsh
-        run: >
-          dotnet test src/Apha.BST/Apha.BST.Application.UnitTests/Apha.BST.Application.UnitTests.csproj `
-            --no-build --configuration Release /p:CollectCoverage=true `
-            /p:CoverletOutput="$($PWD.Path)/src/TestResults/Apha.BST.Application.coverage.opencover.xml" `
-            /p:CoverletOutputFormat=opencover `
-            /p:Deterministic=true `
-            /p:DebugType=full /p:DebugSymbols=true `
-            --logger "trx;LogFileName=$($PWD.Path)/src/TestResults/Apha.BST.Application.test_results.trx"
-
-          dotnet test src/Apha.BST/Apha.BST.Web.UnitTests/Apha.BST.Web.UnitTests.csproj `
-            --no-build --configuration Release /p:CollectCoverage=true `
-            /p:CoverletOutput="$($PWD.Path)/src/TestResults/Apha.BST.Web.coverage.opencover.xml" `
-            /p:CoverletOutputFormat=opencover `
-            /p:Deterministic=true `
-            /p:DebugType=full /p:DebugSymbols=true `
-            --logger "trx;LogFileName=$($PWD.Path)/src/TestResults/Apha.BST.Web.test_results.trx"
-            
-          dotnet test src/Apha.BST/Apha.BST.DataAccess.UnitTests/Apha.BST.DataAccess.UnitTests.csproj `
-            --no-build --configuration Release /p:CollectCoverage=true `
-            /p:CoverletOutput="$($PWD.Path)/src/TestResults/Apha.BST.DataAccess.coverage.opencover.xml" `
-            /p:CoverletOutputFormat=opencover `
-            /p:Deterministic=true `
-            /p:DebugType=full /p:DebugSymbols=true `
-            --logger "trx;LogFileName=$($PWD.Path)/src/TestResults/Apha.BST.DataAccess.test_results.trx"
-      - name: List coverage files
-        shell: pwsh
-        run: Get-ChildItem -Recurse -Filter "*.coverage.opencover.xml"; Get-ChildItem -Recurse -Filter "*.test_results.trx"
-      - name: End Sonar Analysis
-        shell: pwsh
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="$env:SONAR_TOKEN"
-
       - name: Compose image tag
         id: imgtag
         shell: pwsh
@@ -123,80 +32,6 @@ jobs:
         run: |
           echo "Image Tag: ${{ steps.imgtag.outputs.image_tag }}"    
 
-      - name: commit application release version in VERSION file
-        shell: bash
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          if ! grep -Fxq "${{ github.event.inputs.DEVIMAGEVERSION }}" VERSION; then
-            git config user.name "github-actions[bot]"
-            git config user.email "github-actions[bot]@users.noreply.github.com"
-            BRANCH="release/update-version-${{ github.event.inputs.DEVIMAGEVERSION }}-${{ github.run_id }}"
-            echo "${{ github.event.inputs.DEVIMAGEVERSION }}" >| VERSION
-            cat VERSION
-            git add VERSION
-            git commit -m "Update VERSION to ${{ github.event.inputs.DEVIMAGEVERSION }}"
-          else
-            echo "VERSION file already contains ${{ github.event.inputs.DEVIMAGEVERSION }} — skipping commit"
-            exit 1
-          fi
-
-      - name: Create Pull Request
-        id: cpr
-        uses: peter-evans/create-pull-request@v7
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          branch: release/update-version-${{ github.event.inputs.DEVIMAGEVERSION }}-${{ github.run_id }}
-          base: main
-          title: "Release: Update VERSION to ${{ github.event.inputs.DEVIMAGEVERSION }}"
-          body: "This PR updates the VERSION file to ${{ github.event.inputs.DEVIMAGEVERSION }}."
-
-
-      - name: Wait for approval (max 5 minutes)
-        id: wait_for_approval
-        shell: bash
-        run: |
-          pr_number=${{ steps.cpr.outputs.pull-request-number }}
-          echo "Waiting up to 5 minutes for PR #$pr_number approval..."
-          approved=false
-          for i in {1..5}; do
-            sleep 60
-            reviews=$(gh pr view $pr_number --json reviews --jq '.reviews[].state' --repo ${{ github.repository }})
-            echo "Current reviews: $reviews"
-            if echo "$reviews" | grep -q "APPROVED"; then
-              approved=true
-              break
-            fi
-          done
-
-          if [ "$approved" = "false" ]; then
-            echo "No approval after 5 minutes. Closing PR."
-            gh pr close $pr_number --delete-branch --repo ${{ github.repository }}
-            exit 1
-          fi
-
-          echo "PR approved, proceeding..."
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Enable Auto-Merge
-        if: steps.wait_for_approval.outcome == 'success'
-        uses: peter-evans/enable-pull-request-automerge@v3
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
-          merge-method: squash          
-        
-  push-image:
-    name: Push Docker Image
-    needs: build-and-analyze
-    runs-on: ubuntu-latest
-    environment: DEV   # 👈 restrict this job to DEV environment
-    permissions:
-      id-token: write
-      contents: read
-    
-    steps:
       - name: Checkout code
         uses: actions/checkout@v4
         with:
@@ -229,7 +64,7 @@ jobs:
 
       - name: Build and push Docker image manually
         run: |
-          IMAGE_TAG="${{ needs.build-and-analyze.outputs.image_tag }}"
+          IMAGE_TAG="${{ steps.imgtag.outputs.image_tag }}"
           IMAGE_NAME="${{ steps.login-ecr.outputs.registry }}/${{ env.REPOSITORY }}"
           
           GIT_COMMIT="${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}"
@@ -303,3 +138,22 @@ jobs:
         if: always()
         run: |
           docker rm -f test-container
+
+
+      - name: Create and push git tag
+        env:
+          IMAGE_TAG: ${{ steps.imgtag.outputs.image_tag }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          git config user.name "github-actions[bot]"
+          git config user.email "github-actions[bot]@users.noreply.github.com"
+
+          # Create the tag only if it doesn't already exist
+          if git ls-remote --tags origin | grep -q "refs/tags/$IMAGE_TAG"; then
+            echo "Tag $IMAGE_TAG already exists. error..."
+            exit 1
+          else
+            echo "Creating and pushing tag $IMAGE_TAG"
+            git tag "$IMAGE_TAG"
+            git push origin "$IMAGE_TAG"
+          fi    
